### ISSUE TITLE
Cannot get cv to work 

### ISSUE THREAD

**Issue by TWR2020** [MXET/SCUTTLE#41] opened 2019-10-31 15:24 UTC
when we tried to run:
sudo bash start_mjgp_streamer.sh L3_image_filter.py 
we are receiving this error. 

<img width="889" alt="Screen Shot 2019-10-31 at 10 20 15 AM" src="https://user-images.githubusercontent.com/54941239/67960674-a0201980-fbc8-11e9-91a7-3b25839e7229.png">

**Comment by ansarid** [comment] 2019-10-31 15:27
@TWR2020 Please copy and paste the output. Do not attach screenshots of your issue.

**Comment by ansarid** [comment] 2019-11-04 17:52
@TWR2020 If this issue has been resolved please let me know that it has been resolved and what the issue is so that I can close this issue. If I do not get a response within the next day I will consider this issue resolved and the issue can be reopened if that is not the case.

**Comment by TWR2020** [comment] 2019-11-05 15:10
we are still having the same issue here is a copy of the output also. 

debian@scuttle:~/basics/computer_vision$ ls
L3_image_filter.py  start_mjpg_streamer.sh
debian@scuttle:~/basics/computer_vision$ sudo bash start_mjpg_streamer.sh L3_image_filter.py
[sudo] password for debian:
MJPG Streamer Version.: 2.0
ERROR: could not find input plugin
       Perhaps you want to adjust the search path with:
       # export LD_LIBRARY_PATH=/path/to/plugin/folder
       dlopen: /usr/lib/mjpg-streamer/input_opencv.so: cannot open shared object file: No such file or directory
debian@scuttle:~/basics/computer_vision$

**Comment by TWR2020** [comment] 2019-11-05 15:13
we have run both of the self installers also here is the code again.


`debian@scuttle:~/basics/computer_vision$ ls
L3_image_filter.py  start_mjpg_streamer.sh
debian@scuttle:~/basics/computer_vision$ sudo bash start_mjpg_streamer.sh L3_image_filter.py
[sudo] password for debian:
MJPG Streamer Version.: 2.0
ERROR: could not find input plugin
       Perhaps you want to adjust the search path with:
       # export LD_LIBRARY_PATH=/path/to/plugin/folder
       dlopen: /usr/lib/mjpg-streamer/input_opencv.so: cannot open shared object file: No such file or directory
debian@scuttle:~/basics/computer_vision$`

**Comment by ansarid** [comment] 2019-11-05 18:13
@TWR2020 Please run `check_installed.sh` located in the scripts folder  and then try running `bash start_mjpg_streamer.sh L3_image_filter.py` again. Please send me the output of both commands.

**Comment by ansarid** [comment] 2019-11-05 18:13
@TWR2020 Please run `check_installed.sh` located in the scripts folder  and then try running `bash start_mjpg_streamer.sh L3_image_filter.py` again. Please send me the output of both commands.

**Comment by TWR2020** [comment] 2019-11-05 22:17
I ran the check_installed.sh and it installed a line for opencv however after doing this I ran the next command and I now cannot find the output as the terminal history is not long enough. 
When I ran the `bash start_mjpg_streamer.sh L3_image_filter.py` it created a output that had statements about errors in it. When I ran the bordered flow I only saw one video stream image. 

`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/h_min'
Traceback (most recent call last):
  File "./L3_image_filter.py", line 25, in colorTracking
    with open('/tmp/h_min') as h_min_file:`

**Comment by TWR2020** [comment] 2019-11-05 22:26
This is an image of the nodered dashboard 
<img width="1280" alt="Screen Shot 2019-11-05 at 4 24 50 PM" src="https://user-images.githubusercontent.com/54941239/68251541-fd610400-ffe8-11e9-8f67-0559c5be5a45.png">

**Comment by dmalawey** [comment] 2019-11-05 22:51
This image is working properly.  Move the sliders to adjust your mask.

**Comment by dmalawey** [comment] 2019-11-05 22:53
> I ran the check_installed.sh and it installed a line for opencv however after doing this I ran the next command and I now cannot find the output as the terminal history is not long enough.
> When I ran the `bash start_mjpg_streamer.sh L3_image_filter.py` it created a output that had statements about errors in it. When I ran the bordered flow I only saw one video stream image.
> 
> `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/h_min' Traceback (most recent call last): File "./L3_image_filter.py", line 25, in colorTracking with open('/tmp/h_min') as h_min_file:`

@ansarid could we update it to not look for the values until the sliders have been moved once?  Maybe pre-assign some values in the .txt files.

**Comment by TWR2020** [comment] 2019-11-05 23:08
I just figured that out reran it and adjusted the values and everything seems so be working properly.
thank you.

**Comment by ansarid** [comment] 2019-11-06 00:18
Sounds like this issue has been solved.

**Closed as completed by ansarid** 2019-11-06 00:18 UTC
