### ISSUE TITLE
L2_color_target.py producing an error

### ISSUE THREAD

**Issue by destantraeger** [MXET/SCUTTLE#50] opened 2019-11-30 07:53 UTC
code will run properly for several iterations of the standalone loop but will fail the process the 'None' value at some point and produce the following error:

Traceback (most recent call last):
  File "L2_color_target.py", line 53, in <module>
    if target[0] == None:
TypeError: 'NoneType' object is not subscriptable

"x = target[0]" & "if x == None:" were changed in order to attempt to solve the math error, however, it was unsuccessful.

**Comment by ansarid** [comment] 2019-12-02 15:32
@destantraeger I don't see `if target[0] == None:` in any of the `L2_color_target.py`  code. Is this custom? If so, the issue is that you are trying to fetch a value from a `None` type using an index value.

Here's a simplification of what you are attempting to show why it is wrong.
```
array = None
if array[0] == None:
    # do something.
    pass
```
Running it creates this output:
```
Traceback (most recent call last):
  File "issue50example.py", line 2, in <module>
    if array[0] == None:
TypeError: 'NoneType' object is not subscriptable
```

This is because there is no index `0` in the variable `array` because it is currently set to `None`. The `None` type is not a subscribable type (Cannot be addressed using an index value).

**Comment by ansarid** [comment] 2019-12-04 18:14
@destantraeger Has this issue been solved? If I do not get a response within the next day I will close this issue. If this issue has not been resolved, please let me know. If I close this issue and the issue has not been resolved please let me know and I will reopen the issue.

**Closed as completed** 2019-12-11 23:28 UTC
