### ISSUE TITLE
import cv2 error

### ISSUE THREAD

**Issue by destantraeger** [MXET/SCUTTLE#40] opened 2019-10-31 15:06 UTC
Both self_installer_part1.sh and self_installer_part2.sh were run and cv2 was not installed in the user library. This issue persists across multiple teams.

![Screenshot (19)](https://user-images.githubusercontent.com/54677821/67959087-30a92a80-fbc6-11e9-9c8c-a01b0900ef69.png)

**Comment by ansarid** [comment] 2019-10-31 15:28
@destantraeger Please copy and paste the output. Do not attach screenshots of your issue.

**Comment by ansarid** [comment] 2019-11-04 17:52
@destantraeger If this issue has been resolved please let me know that it has been resolved and what the issue is so that I can close this issue. If I do not get a response within the next day I will consider this issue resolved and the issue can be reopened if that is not the case.

**Closed as completed by ansarid** 2019-11-04 17:52 UTC
